#!/usr/bin/env python3

import curses

PAGE_UP = [ord('n'), ord('j'), ord(' ')]
PAGE_DOWN = [ord('p'), ord('k')]
NEXT_CHAPTER = [ord('N'), ord('l')]
PREVIOUS_CHAPTER = [ord('P'), ord('h')]
START_OF_CHAPTER = [ord('g'), ord('0')]
END_OF_CHAPTER = [ord('G'), ord('$')]
DARK_MODE = [ord('r')]
SPEED_MODE = [ord('s')]
HIGHLIGHT = [ord('v')]
DOUBLE_PAGE = [ord('d')]
JUSTIFY_FULL = [ord('f')]
HYPHENATION = [ord('e')]
V_PADDING_UP = [ord('>')]
H_PADDING_UP = [ord('.')]
V_PADDING_DOWN = [ord('<')]
H_PADDING_DOWN = [ord(',')]
PE_LINE_UP = [ord(']')]
PE_LINE_DOWN = [ord('[')]
TOC = [ord('t'), 9]
SELECT = [curses.KEY_ENTER, ord('o'), 13]
HELP = [ord('?'), curses.KEY_F1]
QUICKMARK = [ord('m')]
QUICKMARK_SLOT = [ord(str(x)) for x in range(1, 10)]
QUICKMARK_CLEAR = [ord('c')]
QUICKMARK_ALL = [ord('a')]
BOOKMARK = [ord('b')]
BOOKMARK_NEW = [ord('B'), ord('M')]
BOOKMARK_REMOVE = [ord('x')]
BOOKMARK_EDIT = [ord('e')]
BOOKMARK_DESCRIBE = [ord('l'), ord('d')]
ESCAPE = [curses.KEY_BACKSPACE, 8, 27]
REFRESH = [ord('R'), curses.KEY_F5]
QUIT = [ord('q')]
